#!/usr/bin/env ruby

require 'csv'
require 'optionparser'
require_relative '../lib/csvutil'


CMD = File.basename __FILE__

def print_version
  puts "#{CMD} #{CSVUtil::VERSION}"
  exit
end

options = {}
parser = OptionParser.new do |opts|

  opts.banner = <<EOF
Usage: #{File.basename __FILE__} [options] CSV CSV [...]

Return a new version of the CSV with only the specified rows.

NB: Assumes CSV has headers.

EOF

  opts.on '-v', '--version', "Print #{CMD} and quit" do
    print_version
  end

  opts.on '-o', '--outfile OUTFILE', "Specify an output filename (default: stdout)" do |outfile|
    options[:outfile] = outfile
  end

  opts.on '-s', '--slice SLICE_SPEC', "Row number(s) to slice on; e.g., '50', '50,10', '50..60'" do |slice_spec|
    options[:slice_spec] = slice_spec
  end

  opts.on '-j', '--reject', "Output rows NOT in the slice" do
    options[:reject] = true
  end

  opts.on("-h", "--help", "Prints this help\n\n") do
    puts opts
    exit
  end
end

parser.parse!

if ARGV.any? || $stdin.tty?
  csv_file = ARGV.shift
  abort "Please provide a CSV file" unless csv_file
  abort "Can't find CSV file" unless File.exist? csv_file
  input = open csv_file
else
  input = $stdin
end

CSVUtil::Slice.new(input, **options).process
