#!/usr/bin/env ruby

require 'csv'
require 'optionparser'
require 'tempfile'

require_relative '../lib/csvutil'


CMD = File.basename __FILE__

########################################################################
# Methods
########################################################################
def print_version
  puts "#{CMD} #{CSVUtil::VERSION}"
end

options = {}
parser = OptionParser.new do |opts|

  opts.banner = <<EOF
Usage: #{File.basename __FILE__} [options] CSV CSV [...]

Concatenate two or more CSVs. CSVs must have headers, but the headers don't
have to match. Headers of output CSV will be the unique set of input headers.

    a,b,c  +  c,d,e  =>  a,b,c,d,e
    1,2,3     3,4,5  =>  1,2,3,,
                        ,,3,4,5

Header uniqueness is case sensitve.

NB: Not tested for empty headers:

    name,address,,city,state

Or for non-unique headers in the same CSV; e.g.,

    name,address,city,state,name

EOF

  # version
  version_help = "Print #{CMD} and quit"
  opts.on '-v', '--version', version_help do
    print_version
    exit
  end

  # outfile
  out_help = "Specify an output filename (default: stdout)"
  opts.on '-o', '--outfile OUTFILE', out_help do |outfile|
    options[:outfile] = outfile
  end

  help_help = <<~EOF
    Prints this help

  EOF
  opts.on("-h", "--help", help_help) do
    puts opts
    exit
  end
end

parser.parse!

input = ($stdin.tty? || ARGV.any?) ? ARGV.dup : ARGF

csvs = input.map(&:chomp).map { |f|
  # handle fifos
  if File::ftype(f) == 'fifo'
    tf = Tempfile.new
    tf.puts File.open(f).read
    tf.close
    tf.path
  else
    f
  end
}

cat = CSVUtil::Cat.new *csvs, **options
cat.process
